[package]
name = "stormbreaker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.6", features = ["std", "derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.16"
serde_json = "1.0"
mysql = "23.0.1"
chrono = "0.4.19"
